services:
  - type: web
    name: recad-semiterio-municipal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: onboarding@resend.dev
      - key: TARGET_EMAIL
        value: diegocesare300491@gmail.com
